databases:
  - name: secure-login-db
    plan: free
    databaseName: laravel
    user: laravel

services:
  - type: web
    name: secure-login-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: "Secure Login App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: secure-login-app
          property: url
      - key: TRUSTED_PROXIES
        value: "*"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: secure-login-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: secure-login-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: secure-login-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: secure-login-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: secure-login-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
